const { test, expect } = require('@playwright/test');
const { dockerExec, php } = require('./helpers');
const { webContainer } = require('./env');

test('upgrade script runs without fatal errors', async () => {
  const output = dockerExec(webContainer, ['php', '/var/www/html/upgrade.php']);
  expect(output).toContain('Upgrade complete');
  expect(output).not.toMatch(/Fatal error|Parse error|Warning/i);
});

test('public report token works and expired token is rejected', async ({ page }) => {
  const token = php(`
    define('BASE_PATH', '/var/www/html');
    require_once BASE_PATH . '/config.php';
    require_once BASE_PATH . '/includes/database.php';
    require_once BASE_PATH . '/includes/tenant-functions.php';
    ensure_tenant_baseline();
    require_once BASE_PATH . '/includes/functions.php';
    require_once BASE_PATH . '/includes/settings-functions.php';
    require_once BASE_PATH . '/includes/ticket-share-functions.php';
    function current_user() { return ['id' => 1]; }
    require_once BASE_PATH . '/includes/report-functions.php';
    $tenant_id = function_exists('current_tenant_id') ? current_tenant_id() : null;
    $with_tenant = static function (string $table, array $data) use ($tenant_id): array {
      if ($tenant_id && function_exists('column_exists') && column_exists($table, 'tenant_id')) {
        $data['tenant_id'] = $tenant_id;
      }
      return $data;
    };
    $org = db_insert('organizations', $with_tenant('organizations', ['name' => 'E2E Org', 'is_active' => 1]));
    $status_row = db_fetch_one("SELECT id FROM statuses ORDER BY id ASC LIMIT 1");
    $status = $status_row['id'] ?? null;
    if (!$status) {
      $status = db_insert('statuses', ['name' => 'Open', 'color' => '#3b82f6', 'is_closed' => 0, 'sort_order' => 1]);
    }
    $ticket = db_insert('tickets', $with_tenant('tickets', [
      'hash' => 'e2ereport' . substr(bin2hex(random_bytes(4)), 0, 4),
      'title' => 'E2E ticket summary row',
      'description' => 'Report detail test ticket',
      'user_id' => 1,
      'organization_id' => $org,
      'status_id' => $status,
      'source' => 'web',
      'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
      'updated_at' => date('Y-m-d H:i:s')
    ]));
    $comment = db_insert('comments', $with_tenant('comments', [
      'ticket_id' => $ticket,
      'user_id' => 1,
      'content' => '<p>Prepared customer-facing report detail.</p>',
      'is_internal' => 0,
      'time_spent' => 45,
      'created_at' => date('Y-m-d H:i:s', strtotime('-1 day +45 minutes'))
    ]));
    db_insert('ticket_time_entries', $with_tenant('ticket_time_entries', [
      'ticket_id' => $ticket,
      'user_id' => 1,
      'comment_id' => $comment,
      'started_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
      'ended_at' => date('Y-m-d H:i:s', strtotime('-1 day +45 minutes')),
      'duration_minutes' => 45,
      'is_billable' => 1,
      'billable_rate' => 1200,
      'cost_rate' => 0,
      'is_manual' => 1,
      'summary' => 'Prepared customer-facing report detail',
      'created_at' => date('Y-m-d H:i:s', strtotime('-1 day +45 minutes'))
    ]));
    $report = create_report_template([
      'organization_id' => $org,
      'created_by_user_id' => 1,
      'title' => 'E2E Public Report',
      'date_from' => date('Y-m-d', strtotime('-7 days')),
      'date_to' => date('Y-m-d'),
      'executive_summary' => 'Generated by E2E',
      'is_draft' => 0,
      'expires_at' => date('Y-m-d H:i:s', strtotime('+1 day'))
    ]);
    echo create_report_template_share($report, $org, 1);
  `).trim();

  await page.goto(`/index.php?page=report-public&token=${encodeURIComponent(token)}`);
  await expect(page.locator('body')).toContainText('E2E Public Report');
  await expect(page.locator('[data-report-ticket-row]').first()).toContainText('E2E ticket summary row');
  await page.locator('[data-report-ticket-row]').first().click();
  await expect(page.locator('[data-report-comment-row]').first()).toContainText('Prepared customer-facing report detail');

  php(`
    define('BASE_PATH', '/var/www/html');
    require_once BASE_PATH . '/config.php';
    require_once BASE_PATH . '/includes/database.php';
    db_query("UPDATE report_templates SET expires_at = DATE_SUB(NOW(), INTERVAL 1 DAY) WHERE title = 'E2E Public Report'");
  `);

  const expired = await page.request.get(`/index.php?page=report-public&token=${encodeURIComponent(token)}`);
  expect(expired.status()).toBe(410);
});

test('backup rollback removes files created after backup and health remains OK', async ({ page }) => {
  const output = php(`
    define('BASE_PATH', '/var/www/html');
    require_once BASE_PATH . '/config.php';
    require_once BASE_PATH . '/includes/database.php';
    require_once BASE_PATH . '/includes/functions.php';
    require_once BASE_PATH . '/includes/settings-functions.php';
    require_once BASE_PATH . '/includes/update-functions.php';
    $backup = create_backup();
    if (!$backup['success']) {
      fwrite(STDERR, json_encode($backup));
      exit(2);
    }
    file_put_contents(BASE_PATH . '/rollback-marker-e2e.txt', 'created after backup');
    rollback_update($backup['backup_id'], false);
  `);
  expect(output).toContain('Rollback complete');

  const marker = dockerExec(webContainer, ['sh', '-lc', 'test ! -f /var/www/html/rollback-marker-e2e.txt && echo removed']);
  expect(marker.trim()).toBe('removed');

  const health = await page.request.get('/index.php?page=health');
  expect(health.status()).toBe(200);
  expect(await health.json()).toMatchObject({ status: 'ok', db: true });
});
